// Generated by CoffeeScript 1.3.3
(function() {
  var configFile, configFiles, configName, configPath, fs, fullPath, path, _i, _len;

  path = require('path');

  fs = require('fs');

  require('js-yaml');

  configPath = '../config';

  configFiles = fs.readdirSync(configPath);

  for (_i = 0, _len = configFiles.length; _i < _len; _i++) {
    configFile = configFiles[_i];
    if (path.extname(configFile) !== '.yml' || configFile.indexOf('.sample') !== -1) {
      continue;
    }
    configName = path.basename(configFile, '.yml');
    fullPath = path.join(configPath, configFile);
    exports[configName] = require(fullPath);
  }

}).call(this);
