// Generated by CoffeeScript 1.3.3
(function() {
  var app, config, express;

  config = require('./config');

  express = require('express');

  app = express();

  console.log(config);

  app.get('/', function(req, res) {
    return res.send('hello world!');
  });

  app.listen(3000);

}).call(this);
